version: '3.4'

services:
  retornajuros:
    image: ${DOCKER_REGISTRY-}retornajuros
    ports: 
      - 5000:5000
    build:
      context: .
      dockerfile: CalculaJurosApp/CalculaJurosApp/Dockerfile

  calculajuros:
    image: ${DOCKER_REGISTRY-}calculajuros
    ports: 
      - 5001:5001
    build:
      context: .
      dockerfile: RetornaJurosApp/RetornaJurosApp/Dockerfile